setwd("D:/DRC/gaussian_process_AOC")

rm(list = ls())
gc()
source("./01_create_data_2.R")
rm(list = ls())
gc()
source("./01a_prepare_settlements.R")
rm(list = ls())
gc()
source("./01b_prepare_travelspeed.R")
rm(list = ls())
gc()
source("./01c_prepare_distance_to_rwa.R")
rm(list = ls())
gc()
source("./01d_prepare_landcover.R")
rm(list = ls())
gc()
source("./01e_prepare_acled.R")
rm(list = ls())
gc()
source("./01f_prepare_rain.R")
rm(list = ls())
gc()
source("./02_combine_data.R")
rm(list = ls())
gc()
source("./04a_prepare_inla_data.R")
rm(list = ls())
gc()